server:
  port: 8763
  context-path: /message
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: message
  activemq:
    broker-url: tcp://localhost:61616
    in-memory: true
    pool:
      enabled: false
  mail:
    host: smtp.163.com
    username: 15529041589@163.com
    password: liumiao1024

    properties:
      mail:
       smtp:
      auth: true
      starttls:
      enable: true
      required: true
########################################

msg: 
  subject: 提示您，会员注册成功邮件。
  text:  恭喜您的账户{},注册成功!猜猜我是谁